CREATE TABLE JPA.MEMBERS(
MEMBERS_ID BIGINT PRIMARY KEY,
MEMBERS_USER_ID VARCHAR(255) NOT NULL,
MEMBERS_USER_PASSWORD VARCHAR(255) NOT NULL,
MEMBERS_USER_NICKNAME VARCHAR(255) NOT NULL
);

CREATE TABLE JPA.ACTOR(
ACTOR_ID BIGINT PRIMARY KEY,
ACTOR_NAME VARCHAR(255) NOT NULL,
ACTOR_BIRTH DATE NOT NULL
);

CREATE TABLE JPA.MOVIE(
MOVIE_ID BIGINT PRIMARY KEY,
MOVIE_TITLE VARCHAR(255) NOT NULL,
MOVIE_POSTER TEXT NOT NULL,
MOVIE_CONTENT TEXT NOT NULL,
MOVIE_PREVIEW TEXT NOT NULL,
MOVIE_TOTAL_SCORE INT NOT NULL DEFAULT 0
);

CREATE TABLE JPA.MOVIE_BOARD(
MOVIE_BOARD_ID BIGINT PRIMARY KEY,
MOVIE_ID BIGINT REFERENCES MOVIE (MOVIE_ID),
MEMBERS_ID BIGINT REFERENCES MEMBERS(MEMBERS_ID),
MOVIE_BOARD_CONTENT TEXT NOT NULL,
MOVIE_BOARD_SCORE INT NOT NULL
);

CREATE TABLE JPA.MOVIE_ACTOR(
MOVIE_ID BIGINT REFERENCES MOVIE(MOVIE_ID),
MEMBERS_ID BIGINT REFERENCES MEMBER(MEMBER_ID),
PRIMARY KEY( MOVIE_ID, MEMBERS_ID)
);





